

exports.workDataV16CreatePRHQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON; 

    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='P_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[P_${tarih}_${depoNo}](
      [prh_Guid] [uniqueidentifier] NOT NULL,
      [prh_DBCno] [smallint] NOT NULL,
      [prh_Spec_Rec_no] [int] NULL,
      [prh_iptal] [bit] NULL,
      [prh_fileid] [smallint] NULL,
      [prh_hidden] [bit] NULL,
      [prh_kilitli] [bit] NULL,
      [prh_degisti] [bit] NULL,
      [prh_checksum] [int] NULL,
      [prh_create_user] [smallint] NULL,
      [prh_create_date] [datetime] NOT NULL,
      [prh_lastup_user] [smallint] NULL,
      [prh_lastup_date] [datetime] NULL,
      [prh_special1] [nvarchar](4) NULL,
      [prh_special2] [nvarchar](4) NULL,
      [prh_special3] [nvarchar](4) NULL,
      [prh_firmano] [int] NULL,
      [prh_subeno] [int] NULL,
      [prh_promo_kodu] [nvarchar](25) NULL,
      [prh_evrak_kaynak] [tinyint] NULL,
      [prh_sth_evraktip] [tinyint] NULL,
      [prh_evrak_cins] [tinyint] NULL,
      [prh_sth_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [prh_sth_evrakno_sira] [int] NULL,
      [prh_sth_satirno] [int] NULL,
      [prh_urun_cinsi] [tinyint] NULL,
      [prh_stok_kodu] [nvarchar](25) NULL,
      [prh_cari_kodu] [nvarchar](25) NULL,
      [prh_tarih] [datetime] NULL,
      [prh_plasiyer_kodu] [nvarchar](25) NULL,
      [prh_miktar] [float] NULL,
      [prh_tutar] [float] NULL,
      [prh_yansiyan_promo_tutari] [float] NULL,
      [prh_promosyon_tipi] [smallint] NULL,
      [prh_uygulama_tipi] [smallint] NULL,
    CONSTRAINT [NDX_P_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [prh_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];

    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [prh_Guid];
    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [prh_DBCno];
    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [prh_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'35a' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'P_${tarih}_${depoNo}';
  END
    `
  return q
}

exports.workDataV16CreatePOQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON;
    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='O_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[O_${tarih}_${depoNo}](
      [po_Guid] [uniqueidentifier] NOT NULL,
      [po_DBCno] [smallint] NOT NULL,
      [po_SpecRECno] [int] NULL,
      [po_iptal] [bit] NULL,
      [po_fileid] [smallint] NULL,
      [po_hidden] [bit] NULL,
      [po_kilitli] [bit] NULL,
      [po_degisti] [bit] NULL,
      [po_checksum] [int] NULL,
      [po_create_user] [smallint] NULL,
      [po_create_date] [datetime] NOT NULL,
      [po_lastup_user] [smallint] NULL,
      [po_lastup_date] [datetime] NULL,
      [po_special1] [nvarchar](4) NULL,
      [po_special2] [nvarchar](4) NULL,
      [po_special3] [nvarchar](4) NULL,
      [po_firmano] [int] NULL,
      [po_subeno] [int] NULL,
      [po_KasaKodu] [nvarchar](4) NULL,
      [po_BelgeNo] [int] NULL,
      [po_MyeZNo] [int] NULL,
      [po_KasiyerKodu] [nvarchar](6) NULL,
      [po_BelgeTarihi] [datetime] NULL,
      [po_BelgeToplam] [float] NULL,
      [po_VerMtrh0] [float] NULL,
      [po_VerMtrh1] [float] NULL,
      [po_VerMtrh2] [float] NULL,
      [po_VerMtrh3] [float] NULL,
      [po_VerMtrh4] [float] NULL,
      [po_VerMtrh5] [float] NULL,
      [po_VerMtrh6] [float] NULL,
      [po_VerMtrh7] [float] NULL,
      [po_VerMtrh8] [float] NULL,
      [po_VerMtrh9] [float] NULL,
      [po_VerMtrh10] [float] NULL,
      [po_VerMtrh11] [float] NULL,
      [po_VerMtrh12] [float] NULL,
      [po_VerMtrh13] [float] NULL,
      [po_VerMtrh14] [float] NULL,
      [po_VerMtrh15] [float] NULL,
      [po_VerMtrh16] [float] NULL,
      [po_VerMtrh17] [float] NULL,
      [po_VerMtrh18] [float] NULL,
      [po_VerMtrh19] [float] NULL,
      [po_VerMtrh20] [float] NULL,
      [po_Vergi1] [float] NULL,
      [po_Vergi2] [float] NULL,
      [po_Vergi3] [float] NULL,
      [po_Vergi4] [float] NULL,
      [po_Vergi5] [float] NULL,
      [po_Vergi6] [float] NULL,
      [po_Vergi7] [float] NULL,
      [po_Vergi8] [float] NULL,
      [po_Vergi9] [float] NULL,
      [po_Vergi10] [float] NULL,
      [po_Vergi11] [float] NULL,
      [po_Vergi12] [float] NULL,
      [po_Vergi13] [float] NULL,
      [po_Vergi14] [float] NULL,
      [po_Vergi15] [float] NULL,
      [po_Vergi16] [float] NULL,
      [po_Vergi17] [float] NULL,
      [po_Vergi18] [float] NULL,
      [po_Vergi19] [float] NULL,
      [po_Vergi20] [float] NULL,
      [po_Fisfatura] [tinyint] NULL,
      [po_Pozisyon] [tinyint] NULL,
      [po_CariKodu] [nvarchar](25) NULL,
      [po_Yuvarlama] [float] NULL,
      [po_Odm_AnaDtut1] [float] NULL,
      [po_Odm_OrjDtut1] [float] NULL,
      [po_Odm_AnaDtut2] [float] NULL,
      [po_Odm_OrjDtut2] [float] NULL,
      [po_Odm_AnaDtut3] [float] NULL,
      [po_Odm_OrjDtut3] [float] NULL,
      [po_Odm_AnaDtut4] [float] NULL,
      [po_Odm_OrjDtut4] [float] NULL,
      [po_Odm_AnaDtut5] [float] NULL,
      [po_Odm_OrjDtut5] [float] NULL,
      [po_Odm_AnaDtut6] [float] NULL,
      [po_Odm_OrjDtut6] [float] NULL,
      [po_Odm_AnaDtut7] [float] NULL,
      [po_Odm_OrjDtut7] [float] NULL,
      [po_Odm_AnaDtut8] [float] NULL,
      [po_Odm_OrjDtut8] [float] NULL,
      [po_Odm_AnaDtut9] [float] NULL,
      [po_Odm_OrjDtut9] [float] NULL,
      [po_Odm_AnaDtut10] [float] NULL,
      [po_Odm_OrjDtut10] [float] NULL,
      [po_Odm_AnaDtut11] [float] NULL,
      [po_Odm_OrjDtut11] [float] NULL,
      [po_Odm_AnaDtut12] [float] NULL,
      [po_Odm_OrjDtut12] [float] NULL,
      [po_Odm_AnaDtut13] [float] NULL,
      [po_Odm_OrjDtut13] [float] NULL,
      [po_Odm_AnaDtut14] [float] NULL,
      [po_Odm_OrjDtut14] [float] NULL,
      [po_Odm_AnaDtut15] [float] NULL,
      [po_Odm_OrjDtut15] [float] NULL,
      [po_Odm_AnaDtut16] [float] NULL,
      [po_Odm_OrjDtut16] [float] NULL,
      [po_Odm_AnaDtut17] [float] NULL,
      [po_Odm_OrjDtut17] [float] NULL,
      [po_Odm_AnaDtut18] [float] NULL,
      [po_Odm_OrjDtut18] [float] NULL,
      [po_Odm_AnaDtut19] [float] NULL,
      [po_Odm_OrjDtut19] [float] NULL,
      [po_Odm_AnaDtut20] [float] NULL,
      [po_Odm_OrjDtut20] [float] NULL,
      [po_Odm_AnaDtut21] [float] NULL,
      [po_Odm_OrjDtut21] [float] NULL,
      [po_Odm_AnaDtut22] [float] NULL,
      [po_Odm_OrjDtut22] [float] NULL,
      [po_Odm_AnaDtut23] [float] NULL,
      [po_Odm_OrjDtut23] [float] NULL,
      [po_Odm_AnaDtut24] [float] NULL,
      [po_Odm_OrjDtut24] [float] NULL,
      [po_Odm_AnaDtut25] [float] NULL,
      [po_Odm_OrjDtut25] [float] NULL,
      [po_Odm_AnaDtut26] [float] NULL,
      [po_Odm_OrjDtut26] [float] NULL,
      [po_Odm_AnaDtut27] [float] NULL,
      [po_Odm_OrjDtut27] [float] NULL,
      [po_Odm_AnaDtut28] [float] NULL,
      [po_Odm_OrjDtut28] [float] NULL,
      [po_Odm_AnaDtut29] [float] NULL,
      [po_Odm_OrjDtut29] [float] NULL,
      [po_Odm_AnaDtut30] [float] NULL,
      [po_Odm_OrjDtut30] [float] NULL,
      [po_Odm_AnaDtut31] [float] NULL,
      [po_Odm_OrjDtut31] [float] NULL,
      [po_Odm_AnaDtut32] [float] NULL,
      [po_Odm_OrjDtut32] [float] NULL,
      [po_Odm_AnaDtut33] [float] NULL,
      [po_Odm_OrjDtut33] [float] NULL,
      [po_Odm_AnaDtut34] [float] NULL,
      [po_Odm_OrjDtut34] [float] NULL,
      [po_Odm_AnaDtut35] [float] NULL,
      [po_Odm_OrjDtut35] [float] NULL,
      [po_Odm_AnaDtut36] [float] NULL,
      [po_Odm_OrjDtut36] [float] NULL,
      [po_Odm_AnaDtut37] [float] NULL,
      [po_Odm_OrjDtut37] [float] NULL,
      [po_Odm_AnaDtut38] [float] NULL,
      [po_Odm_OrjDtut38] [float] NULL,
      [po_Odm_AnaDtut39] [float] NULL,
      [po_Odm_OrjDtut39] [float] NULL,
      [po_Odm_AnaDtut40] [float] NULL,
      [po_Odm_OrjDtut40] [float] NULL,
      [po_Odm_AnaDtut41] [float] NULL,
      [po_Odm_OrjDtut41] [float] NULL,
      [po_Odm_AnaDtut42] [float] NULL,
      [po_Odm_OrjDtut42] [float] NULL,
      [po_Odm_AnaDtut43] [float] NULL,
      [po_Odm_OrjDtut43] [float] NULL,
      [po_Odm_AnaDtut44] [float] NULL,
      [po_Odm_OrjDtut44] [float] NULL,
      [po_Odm_AnaDtut45] [float] NULL,
      [po_Odm_OrjDtut45] [float] NULL,
      [po_Odm_AnaDtut46] [float] NULL,
      [po_Odm_OrjDtut46] [float] NULL,
      [po_Odm_AnaDtut47] [float] NULL,
      [po_Odm_OrjDtut47] [float] NULL,
      [po_Odm_AnaDtut48] [float] NULL,
      [po_Odm_OrjDtut48] [float] NULL,
      [po_Odm_AnaDtut49] [float] NULL,
      [po_Odm_OrjDtut49] [float] NULL,
      [po_Odm_AnaDtut50] [float] NULL,
      [po_Odm_OrjDtut50] [float] NULL,
      [po_Vadeler_OdemeTipi1] [tinyint] NULL,
      [po_Vadeler_vade1] [datetime] NULL,
      [po_Vadeler_Tutar1] [float] NULL,
      [po_Vadeler_OdemeTipi2] [tinyint] NULL,
      [po_Vadeler_vade2] [datetime] NULL,
      [po_Vadeler_Tutar2] [float] NULL,
      [po_Vadeler_OdemeTipi3] [tinyint] NULL,
      [po_Vadeler_vade3] [datetime] NULL,
      [po_Vadeler_Tutar3] [float] NULL,
      [po_Vadeler_OdemeTipi4] [tinyint] NULL,
      [po_Vadeler_vade4] [datetime] NULL,
      [po_Vadeler_Tutar4] [float] NULL,
      [po_Vadeler_OdemeTipi5] [tinyint] NULL,
      [po_Vadeler_vade5] [datetime] NULL,
      [po_Vadeler_Tutar5] [float] NULL,
      [po_Vadeler_OdemeTipi6] [tinyint] NULL,
      [po_Vadeler_vade6] [datetime] NULL,
      [po_Vadeler_Tutar6] [float] NULL,
      [po_Vadeler_OdemeTipi7] [tinyint] NULL,
      [po_Vadeler_vade7] [datetime] NULL,
      [po_Vadeler_Tutar7] [float] NULL,
      [po_Vadeler_OdemeTipi8] [tinyint] NULL,
      [po_Vadeler_vade8] [datetime] NULL,
      [po_Vadeler_Tutar8] [float] NULL,
      [po_Vadeler_OdemeTipi9] [tinyint] NULL,
      [po_Vadeler_vade9] [datetime] NULL,
      [po_Vadeler_Tutar9] [float] NULL,
      [po_Vadeler_OdemeTipi10] [tinyint] NULL,
      [po_Vadeler_vade10] [datetime] NULL,
      [po_Vadeler_Tutar10] [float] NULL,
      [po_Vadeler_OdemeTipi11] [tinyint] NULL,
      [po_Vadeler_vade11] [datetime] NULL,
      [po_Vadeler_Tutar11] [float] NULL,
      [po_Vadeler_OdemeTipi12] [tinyint] NULL,
      [po_Vadeler_vade12] [datetime] NULL,
      [po_Vadeler_Tutar12] [float] NULL,
      [po_Vadeler_OdemeTipi13] [tinyint] NULL,
      [po_Vadeler_vade13] [datetime] NULL,
      [po_Vadeler_Tutar13] [float] NULL,
      [po_Vadeler_OdemeTipi14] [tinyint] NULL,
      [po_Vadeler_vade14] [datetime] NULL,
      [po_Vadeler_Tutar14] [float] NULL,
      [po_Vadeler_OdemeTipi15] [tinyint] NULL,
      [po_Vadeler_vade15] [datetime] NULL,
      [po_Vadeler_Tutar15] [float] NULL,
      [po_Vadeler_OdemeTipi16] [tinyint] NULL,
      [po_Vadeler_vade16] [datetime] NULL,
      [po_Vadeler_Tutar16] [float] NULL,
      [po_Vadeler_OdemeTipi17] [tinyint] NULL,
      [po_Vadeler_vade17] [datetime] NULL,
      [po_Vadeler_Tutar17] [float] NULL,
      [po_Vadeler_OdemeTipi18] [tinyint] NULL,
      [po_Vadeler_vade18] [datetime] NULL,
      [po_Vadeler_Tutar18] [float] NULL,
      [po_Vadeler_OdemeTipi19] [tinyint] NULL,
      [po_Vadeler_vade19] [datetime] NULL,
      [po_Vadeler_Tutar19] [float] NULL,
      [po_Vadeler_OdemeTipi20] [tinyint] NULL,
      [po_Vadeler_vade20] [datetime] NULL,
      [po_Vadeler_Tutar20] [float] NULL,
      [po_Vadeler_OdemeTipi21] [tinyint] NULL,
      [po_Vadeler_vade21] [datetime] NULL,
      [po_Vadeler_Tutar21] [float] NULL,
      [po_Vadeler_OdemeTipi22] [tinyint] NULL,
      [po_Vadeler_vade22] [datetime] NULL,
      [po_Vadeler_Tutar22] [float] NULL,
      [po_Vadeler_OdemeTipi23] [tinyint] NULL,
      [po_Vadeler_vade23] [datetime] NULL,
      [po_Vadeler_Tutar23] [float] NULL,
      [po_Vadeler_OdemeTipi24] [tinyint] NULL,
      [po_Vadeler_vade24] [datetime] NULL,
      [po_Vadeler_Tutar24] [float] NULL,
      [po_Vadeler_OdemeTipi25] [tinyint] NULL,
      [po_Vadeler_vade25] [datetime] NULL,
      [po_Vadeler_Tutar25] [float] NULL,
      [po_Vadeler_OdemeTipi26] [tinyint] NULL,
      [po_Vadeler_vade26] [datetime] NULL,
      [po_Vadeler_Tutar26] [float] NULL,
      [po_Vadeler_OdemeTipi27] [tinyint] NULL,
      [po_Vadeler_vade27] [datetime] NULL,
      [po_Vadeler_Tutar27] [float] NULL,
      [po_Vadeler_OdemeTipi28] [tinyint] NULL,
      [po_Vadeler_vade28] [datetime] NULL,
      [po_Vadeler_Tutar28] [float] NULL,
      [po_Vadeler_OdemeTipi29] [tinyint] NULL,
      [po_Vadeler_vade29] [datetime] NULL,
      [po_Vadeler_Tutar29] [float] NULL,
      [po_Vadeler_OdemeTipi30] [tinyint] NULL,
      [po_Vadeler_vade30] [datetime] NULL,
      [po_Vadeler_Tutar30] [float] NULL,
      [po_Vadeler_OdemeTipi31] [tinyint] NULL,
      [po_Vadeler_vade31] [datetime] NULL,
      [po_Vadeler_Tutar31] [float] NULL,
      [po_Vadeler_OdemeTipi32] [tinyint] NULL,
      [po_Vadeler_vade32] [datetime] NULL,
      [po_Vadeler_Tutar32] [float] NULL,
      [po_Vadeler_OdemeTipi33] [tinyint] NULL,
      [po_Vadeler_vade33] [datetime] NULL,
      [po_Vadeler_Tutar33] [float] NULL,
      [po_Vadeler_OdemeTipi34] [tinyint] NULL,
      [po_Vadeler_vade34] [datetime] NULL,
      [po_Vadeler_Tutar34] [float] NULL,
      [po_Vadeler_OdemeTipi35] [tinyint] NULL,
      [po_Vadeler_vade35] [datetime] NULL,
      [po_Vadeler_Tutar35] [float] NULL,
      [po_Vadeler_OdemeTipi36] [tinyint] NULL,
      [po_Vadeler_vade36] [datetime] NULL,
      [po_Vadeler_Tutar36] [float] NULL,
      [po_Tks_Satis] [bit] NULL,
      [po_Tks_Satis_Tutar] [float] NULL,
      [po_Odm_TaksitTipi1] [tinyint] NULL,
      [po_Odm_TaksitTipi2] [tinyint] NULL,
      [po_Odm_TaksitTipi3] [tinyint] NULL,
      [po_Odm_TaksitTipi4] [tinyint] NULL,
      [po_Odm_TaksitTipi5] [tinyint] NULL,
      [po_Odm_TaksitTipi6] [tinyint] NULL,
      [po_Odm_TaksitTipi7] [tinyint] NULL,
      [po_Odm_TaksitTipi8] [tinyint] NULL,
      [po_Odm_TaksitTipi9] [tinyint] NULL,
      [po_Odm_TaksitTipi10] [tinyint] NULL,
      [po_Odm_TaksitTipi11] [tinyint] NULL,
      [po_Odm_TaksitTipi12] [tinyint] NULL,
      [po_Odm_TaksitTipi13] [tinyint] NULL,
      [po_Odm_TaksitTipi14] [tinyint] NULL,
      [po_Odm_TaksitTipi15] [tinyint] NULL,
      [po_Odm_TaksitTipi16] [tinyint] NULL,
      [po_Odm_TaksitTipi17] [tinyint] NULL,
      [po_Odm_TaksitTipi18] [tinyint] NULL,
      [po_Odm_TaksitTipi19] [tinyint] NULL,
      [po_Odm_TaksitTipi20] [tinyint] NULL,
      [po_Odm_TaksitTipi21] [tinyint] NULL,
      [po_Odm_TaksitTipi22] [tinyint] NULL,
      [po_Odm_TaksitTipi23] [tinyint] NULL,
      [po_Odm_TaksitTipi24] [tinyint] NULL,
      [po_Odm_TaksitTipi25] [tinyint] NULL,
      [po_Odm_TaksitTipi26] [tinyint] NULL,
      [po_Odm_TaksitTipi27] [tinyint] NULL,
      [po_Odm_TaksitTipi28] [tinyint] NULL,
      [po_Odm_TaksitTipi29] [tinyint] NULL,
      [po_Odm_TaksitTipi30] [tinyint] NULL,
      [po_Odm_TaksitTipi31] [tinyint] NULL,
      [po_Odm_TaksitTipi32] [tinyint] NULL,
      [po_Odm_TaksitTipi33] [tinyint] NULL,
      [po_Odm_TaksitTipi34] [tinyint] NULL,
      [po_Odm_TaksitTipi35] [tinyint] NULL,
      [po_Odm_TaksitTipi36] [tinyint] NULL,
      [po_Odm_TaksitTipi37] [tinyint] NULL,
      [po_Odm_TaksitTipi38] [tinyint] NULL,
      [po_Odm_TaksitTipi39] [tinyint] NULL,
      [po_Odm_TaksitTipi40] [tinyint] NULL,
      [po_Odm_TaksitTipi41] [tinyint] NULL,
      [po_Odm_TaksitTipi42] [tinyint] NULL,
      [po_Odm_TaksitTipi43] [tinyint] NULL,
      [po_Odm_TaksitTipi44] [tinyint] NULL,
      [po_Odm_TaksitTipi45] [tinyint] NULL,
      [po_Odm_TaksitTipi46] [tinyint] NULL,
      [po_Odm_TaksitTipi47] [tinyint] NULL,
      [po_Odm_TaksitTipi48] [tinyint] NULL,
      [po_Odm_TaksitTipi49] [tinyint] NULL,
      [po_Odm_TaksitTipi50] [tinyint] NULL,
      [po_OdemeNo1] [tinyint] NULL,
      [po_ProvizyonKodu1] [nvarchar](10) NULL,
      [po_ProvizyonTutari1] [float] NULL,
      [po_OdemeNo2] [tinyint] NULL,
      [po_ProvizyonKodu2] [nvarchar](10) NULL,
      [po_ProvizyonTutari2] [float] NULL,
      [po_OdemeNo3] [tinyint] NULL,
      [po_ProvizyonKodu3] [nvarchar](10) NULL,
      [po_ProvizyonTutari3] [float] NULL,
      [po_OdemeNo4] [tinyint] NULL,
      [po_ProvizyonKodu4] [nvarchar](10) NULL,
      [po_ProvizyonTutari4] [float] NULL,
      [po_OdemeNo5] [tinyint] NULL,
      [po_ProvizyonKodu5] [nvarchar](10) NULL,
      [po_ProvizyonTutari5] [float] NULL,
      [po_OdemeNo6] [tinyint] NULL,
      [po_ProvizyonKodu6] [nvarchar](10) NULL,
      [po_ProvizyonTutari6] [float] NULL,
      [po_Tahsilat_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [po_Tahsilat_evrakno_sira] [int] NULL,
      [po_Tahsilat_Tutari] [float] NULL,
      [po_ParaUstuOdemeTipi] [tinyint] NULL,
      [po_ParaUstuAnaDtut] [float] NULL,
      [po_ParaUstuOrjDtut] [float] NULL,
      [po_EvrakID] [nvarchar](40) NULL,
      [po_AdresNo] [int] NULL,
      [po_EArsivSeri] [nvarchar](7) NULL,
      [po_EArsivSira] [int] NULL,
      [po_ZNo] [int] NULL,
      [po_FNo] [int] NULL,
      [po_EJNo] [int] NULL,
      [po_OKCEvrakID] [nvarchar](40) NULL,
      [po_YolcuBeraberKod] [nvarchar](25) NULL,
      [po_YolcuBeraberIstisnaKodu] [nvarchar](5) NULL,
      [po_YolcuBeraberAraciKurumKodu] [nvarchar](25) NULL,
      [po_GibeGonderildiFl] [bit] NULL,
      [po_KayitSiraNo] [int] IDENTITY(1,1) NOT NULL,
    CONSTRAINT [NDX_O_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [po_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];
    
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [po_Guid];
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [po_DBCno];
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [po_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'33a' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'O_${tarih}_${depoNo}';
    CREATE UNIQUE NONCLUSTERED INDEX [NDX_O_${tarih}_${depoNo}_02] ON [dbo].[O_${tarih}_${depoNo}]([po_KasaKodu] ASC,[po_BelgeNo] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
  END
    `
  return q
}

exports.workDataV16CreateSTHQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON;
    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='S_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[S_${tarih}_${depoNo}](
      [sth_Guid] [uniqueidentifier] NOT NULL,
      [sth_DBCno] [smallint] NOT NULL,
      [sth_SpecRECno] [int] NULL,
      [sth_iptal] [bit] NULL,
      [sth_fileid] [smallint] NULL,
      [sth_hidden] [bit] NULL,
      [sth_kilitli] [bit] NULL,
      [sth_degisti] [bit] NULL,
      [sth_checksum] [int] NULL,
      [sth_create_user] [smallint] NULL,
      [sth_create_date] [datetime] NOT NULL,
      [sth_lastup_user] [smallint] NULL,
      [sth_lastup_date] [datetime] NULL,
      [sth_special1] [nvarchar](4) NULL,
      [sth_special2] [nvarchar](4) NULL,
      [sth_special3] [nvarchar](4) NULL,
      [sth_firmano] [int] NULL,
      [sth_subeno] [int] NULL,
      [sth_tarih] [datetime] NULL,
      [sth_tip] [tinyint] NULL,
      [sth_cins] [tinyint] NULL,
      [sth_normal_iade] [tinyint] NULL,
      [sth_evraktip] [tinyint] NULL,
      [sth_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [sth_evrakno_sira] [int] NULL,
      [sth_satirno] [int] NULL,
      [sth_belge_no] [dbo].[belgeno_str] NULL,
      [sth_belge_tarih] [datetime] NULL,
      [sth_stok_kod] [nvarchar](25) NULL,
      [sth_isk_mas1] [tinyint] NULL,
      [sth_isk_mas2] [tinyint] NULL,
      [sth_isk_mas3] [tinyint] NULL,
      [sth_isk_mas4] [tinyint] NULL,
      [sth_isk_mas5] [tinyint] NULL,
      [sth_isk_mas6] [tinyint] NULL,
      [sth_isk_mas7] [tinyint] NULL,
      [sth_isk_mas8] [tinyint] NULL,
      [sth_isk_mas9] [tinyint] NULL,
      [sth_isk_mas10] [tinyint] NULL,
      [sth_sat_iskmas1] [bit] NULL,
      [sth_sat_iskmas2] [bit] NULL,
      [sth_sat_iskmas3] [bit] NULL,
      [sth_sat_iskmas4] [bit] NULL,
      [sth_sat_iskmas5] [bit] NULL,
      [sth_sat_iskmas6] [bit] NULL,
      [sth_sat_iskmas7] [bit] NULL,
      [sth_sat_iskmas8] [bit] NULL,
      [sth_sat_iskmas9] [bit] NULL,
      [sth_sat_iskmas10] [bit] NULL,
      [sth_pos_satis] [tinyint] NULL,
      [sth_promosyon_fl] [bit] NULL,
      [sth_cari_cinsi] [tinyint] NULL,
      [sth_cari_kodu] [nvarchar](25) NULL,
      [sth_cari_grup_no] [tinyint] NULL,
      [sth_isemri_gider_kodu] [nvarchar](25) NULL,
      [sth_plasiyer_kodu] [nvarchar](25) NULL,
      [sth_har_doviz_cinsi] [tinyint] NULL,
      [sth_har_doviz_kuru] [float] NULL,
      [sth_alt_doviz_kuru] [float] NULL,
      [sth_stok_doviz_cinsi] [tinyint] NULL,
      [sth_stok_doviz_kuru] [float] NULL,
      [sth_miktar] [float] NULL,
      [sth_miktar2] [float] NULL,
      [sth_birim_pntr] [tinyint] NULL,
      [sth_tutar] [float] NULL,
      [sth_iskonto1] [float] NULL,
      [sth_iskonto2] [float] NULL,
      [sth_iskonto3] [float] NULL,
      [sth_iskonto4] [float] NULL,
      [sth_iskonto5] [float] NULL,
      [sth_iskonto6] [float] NULL,
      [sth_masraf1] [float] NULL,
      [sth_masraf2] [float] NULL,
      [sth_masraf3] [float] NULL,
      [sth_masraf4] [float] NULL,
      [sth_vergi_pntr] [tinyint] NULL,
      [sth_vergi] [float] NULL,
      [sth_masraf_vergi_pntr] [tinyint] NULL,
      [sth_masraf_vergi] [float] NULL,
      [sth_netagirlik] [float] NULL,
      [sth_odeme_op] [int] NULL,
      [sth_aciklama] [nvarchar](50) NULL,
      [sth_sip_uid] [uniqueidentifier] NULL,
      [sth_fat_uid] [uniqueidentifier] NULL,
      [sth_giris_depo_no] [int] NULL,
      [sth_cikis_depo_no] [int] NULL,
      [sth_malkbl_sevk_tarihi] [datetime] NULL,
      [sth_cari_srm_merkezi] [nvarchar](25) NULL,
      [sth_stok_srm_merkezi] [nvarchar](25) NULL,
      [sth_fis_tarihi] [datetime] NULL,
      [sth_fis_sirano] [int] NULL,
      [sth_vergisiz_fl] [bit] NULL,
      [sth_maliyet_ana] [float] NULL,
      [sth_maliyet_alternatif] [float] NULL,
      [sth_maliyet_orjinal] [float] NULL,
      [sth_adres_no] [int] NULL,
      [sth_parti_kodu] [nvarchar](25) NULL,
      [sth_lot_no] [int] NULL,
      [sth_kons_uid] [uniqueidentifier] NULL,
      [sth_proje_kodu] [nvarchar](25) NULL,
      [sth_exim_kodu] [nvarchar](25) NULL,
      [sth_otv_pntr] [tinyint] NULL,
      [sth_otv_vergi] [float] NULL,
      [sth_brutagirlik] [float] NULL,
      [sth_disticaret_turu] [tinyint] NULL,
      [sth_otvtutari] [float] NULL,
      [sth_otvvergisiz_fl] [bit] NULL,
      [sth_oiv_pntr] [tinyint] NULL,
      [sth_oiv_vergi] [float] NULL,
      [sth_oivvergisiz_fl] [bit] NULL,
      [sth_fiyat_liste_no] [int] NULL,
      [sth_oivtutari] [float] NULL,
      [sth_Tevkifat_turu] [tinyint] NULL,
      [sth_nakliyedeposu] [int] NULL,
      [sth_nakliyedurumu] [tinyint] NULL,
      [sth_yetkili_uid] [uniqueidentifier] NULL,
      [sth_taxfree_fl] [bit] NULL,
      [sth_ilave_edilecek_kdv] [float] NULL,
      [sth_ismerkezi_kodu] [nvarchar](25) NULL,
      [sth_HareketGrupKodu1] [nvarchar](25) NULL,
      [sth_HareketGrupKodu2] [nvarchar](25) NULL,
      [sth_HareketGrupKodu3] [nvarchar](25) NULL,
      [sth_Olcu1] [float] NULL,
      [sth_Olcu2] [float] NULL,
      [sth_Olcu3] [float] NULL,
      [sth_Olcu4] [float] NULL,
      [sth_Olcu5] [float] NULL,
      [sth_FormulMiktarNo] [tinyint] NULL,
      [sth_FormulMiktar] [float] NULL,
      [sth_eirs_senaryo] [tinyint] NULL,
      [sth_eirs_tipi] [tinyint] NULL,
      [sth_teslim_tarihi] [datetime] NULL,
      [sth_matbu_fl] [bit] NULL,
      [sth_satis_fiyat_doviz_cinsi] [tinyint] NULL,
      [sth_satis_fiyat_doviz_kuru] [float] NULL,
      [sth_eticaret_kanal_kodu] [nvarchar](25) NULL,
      [sth_bagli_ithalat_kodu] [nvarchar](25) NULL,
      [sth_tevkifat_sifirlandi_fl] [bit] NULL,
    CONSTRAINT [NDX_S_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [sth_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [sth_Guid];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [sth_DBCno];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [sth_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'37a' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'S_${tarih}_${depoNo}';
  END
    `
  return q
}


exports.workDataV17CreatePRHQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON; 

    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='P_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[P_${tarih}_${depoNo}](
      [prh_Guid] [uniqueidentifier] NOT NULL,
      [prh_DBCno] [smallint] NOT NULL,
      [prh_Spec_Rec_no] [int] NULL,
      [prh_iptal] [bit] NULL,
      [prh_fileid] [smallint] NULL,
      [prh_hidden] [bit] NULL,
      [prh_kilitli] [bit] NULL,
      [prh_degisti] [bit] NULL,
      [prh_checksum] [int] NULL,
      [prh_create_user] [smallint] NULL,
      [prh_create_date] [datetime] NOT NULL,
      [prh_lastup_user] [smallint] NULL,
      [prh_lastup_date] [datetime] NULL,
      [prh_special1] [nvarchar](127) NULL,
      [prh_special2] [nvarchar](127) NULL,
      [prh_special3] [nvarchar](127) NULL,
      [prh_MainProgramNo] [smallint] NULL,
      [prh_VersionNo] [nvarchar](10) NULL,
      [prh_MenuNo] [nvarchar](10) NULL,
      [prh_MikroSpecial1] [nvarchar](40) NULL,
      [prh_MikroSpecial2] [nvarchar](40) NULL,
      [prh_MikroSpecial3] [nvarchar](40) NULL,
      [prh_ExternalProgramType] [tinyint] NULL,
      [prh_ExternalProgramId] [nvarchar](127) NULL,
      [prh_Hash] [bigint] NULL,
      [prh_firmano] [int] NULL,
      [prh_subeno] [int] NULL,
      [prh_promo_kodu] [nvarchar](25) NULL,
      [prh_evrak_kaynak] [tinyint] NULL,
      [prh_sth_evraktip] [tinyint] NULL,
      [prh_evrak_cins] [tinyint] NULL,
      [prh_sth_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [prh_sth_evrakno_sira] [int] NULL,
      [prh_sth_satirno] [int] NULL,
      [prh_urun_cinsi] [tinyint] NULL,
      [prh_stok_kodu] [nvarchar](25) NULL,
      [prh_cari_kodu] [nvarchar](25) NULL,
      [prh_tarih] [datetime] NULL,
      [prh_plasiyer_kodu] [nvarchar](25) NULL,
      [prh_miktar] [float] NULL,
      [prh_tutar] [float] NULL,
      [prh_yansiyan_promo_tutari] [float] NULL,
      [prh_promosyon_tipi] [smallint] NULL,
      [prh_uygulama_tipi] [smallint] NULL,
    CONSTRAINT [NDX_P_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [prh_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];

    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [prh_Guid];
    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [prh_DBCno];
    ALTER TABLE [dbo].[P_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [prh_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'03d' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'P_${tarih}_${depoNo}';
    CREATE NONCLUSTERED INDEX [NDX_P_${tarih}_${depoNo}_02] ON [dbo].[P_${tarih}_${depoNo}]([prh_promo_kodu] ASC,[prh_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_P_${tarih}_${depoNo}_03] ON [dbo].[P_${tarih}_${depoNo}]([prh_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_P_${tarih}_${depoNo}_04] ON [dbo].[P_${tarih}_${depoNo}]([prh_stok_kodu] ASC,[prh_promosyon_tipi] ASC,[prh_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_P_${tarih}_${depoNo}_05] ON [dbo].[P_${tarih}_${depoNo}]([prh_tarih] ASC,[prh_sth_evraktip] ASC,[prh_sth_evrakno_seri] ASC,[prh_sth_evrakno_sira] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_P_${tarih}_${depoNo}_06] ON [dbo].[P_${tarih}_${depoNo}]([prh_cari_kodu] ASC,[prh_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
  END
    `
  return q
}

exports.workDataV17CreatePOQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON;
    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='O_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[O_${tarih}_${depoNo}](
      [po_Guid] [uniqueidentifier] NOT NULL,
      [po_DBCno] [smallint] NOT NULL,
      [po_SpecRECno] [int] NULL,
      [po_iptal] [bit] NULL,
      [po_fileid] [smallint] NULL,
      [po_hidden] [bit] NULL,
      [po_kilitli] [bit] NULL,
      [po_degisti] [bit] NULL,
      [po_checksum] [int] NULL,
      [po_create_user] [smallint] NULL,
      [po_create_date] [datetime] NOT NULL,
      [po_lastup_user] [smallint] NULL,
      [po_lastup_date] [datetime] NULL,
      [po_special1] [nvarchar](127) NULL,
      [po_special2] [nvarchar](127) NULL,
      [po_special3] [nvarchar](127) NULL,
      [po_MainProgramNo] [smallint] NULL,
      [po_VersionNo] [nvarchar](10) NULL,
      [po_MenuNo] [nvarchar](10) NULL,
      [po_MikroSpecial1] [nvarchar](40) NULL,
      [po_MikroSpecial2] [nvarchar](40) NULL,
      [po_MikroSpecial3] [nvarchar](40) NULL,
      [po_ExternalProgramType] [tinyint] NULL,
      [po_ExternalProgramId] [nvarchar](127) NULL,
      [po_Hash] [bigint] NULL,
      [po_firmano] [int] NULL,
      [po_subeno] [int] NULL,
      [po_KasaKodu] [nvarchar](4) NULL,
      [po_BelgeNo] [int] NULL,
      [po_MyeZNo] [int] NULL,
      [po_KasiyerKodu] [nvarchar](6) NULL,
      [po_BelgeTarihi] [datetime] NULL,
      [po_BelgeToplam] [float] NULL,
      [po_VerMtrh0] [float] NULL,
      [po_VerMtrh1] [float] NULL,
      [po_VerMtrh2] [float] NULL,
      [po_VerMtrh3] [float] NULL,
      [po_VerMtrh4] [float] NULL,
      [po_VerMtrh5] [float] NULL,
      [po_VerMtrh6] [float] NULL,
      [po_VerMtrh7] [float] NULL,
      [po_VerMtrh8] [float] NULL,
      [po_VerMtrh9] [float] NULL,
      [po_VerMtrh10] [float] NULL,
      [po_VerMtrh11] [float] NULL,
      [po_VerMtrh12] [float] NULL,
      [po_VerMtrh13] [float] NULL,
      [po_VerMtrh14] [float] NULL,
      [po_VerMtrh15] [float] NULL,
      [po_VerMtrh16] [float] NULL,
      [po_VerMtrh17] [float] NULL,
      [po_VerMtrh18] [float] NULL,
      [po_VerMtrh19] [float] NULL,
      [po_VerMtrh20] [float] NULL,
      [po_Vergi1] [float] NULL,
      [po_Vergi2] [float] NULL,
      [po_Vergi3] [float] NULL,
      [po_Vergi4] [float] NULL,
      [po_Vergi5] [float] NULL,
      [po_Vergi6] [float] NULL,
      [po_Vergi7] [float] NULL,
      [po_Vergi8] [float] NULL,
      [po_Vergi9] [float] NULL,
      [po_Vergi10] [float] NULL,
      [po_Vergi11] [float] NULL,
      [po_Vergi12] [float] NULL,
      [po_Vergi13] [float] NULL,
      [po_Vergi14] [float] NULL,
      [po_Vergi15] [float] NULL,
      [po_Vergi16] [float] NULL,
      [po_Vergi17] [float] NULL,
      [po_Vergi18] [float] NULL,
      [po_Vergi19] [float] NULL,
      [po_Vergi20] [float] NULL,
      [po_Fisfatura] [tinyint] NULL,
      [po_Pozisyon] [tinyint] NULL,
      [po_CariKodu] [nvarchar](25) NULL,
      [po_Yuvarlama] [float] NULL,
      [po_Odm_AnaDtut1] [float] NULL,
      [po_Odm_OrjDtut1] [float] NULL,
      [po_Odm_AnaDtut2] [float] NULL,
      [po_Odm_OrjDtut2] [float] NULL,
      [po_Odm_AnaDtut3] [float] NULL,
      [po_Odm_OrjDtut3] [float] NULL,
      [po_Odm_AnaDtut4] [float] NULL,
      [po_Odm_OrjDtut4] [float] NULL,
      [po_Odm_AnaDtut5] [float] NULL,
      [po_Odm_OrjDtut5] [float] NULL,
      [po_Odm_AnaDtut6] [float] NULL,
      [po_Odm_OrjDtut6] [float] NULL,
      [po_Odm_AnaDtut7] [float] NULL,
      [po_Odm_OrjDtut7] [float] NULL,
      [po_Odm_AnaDtut8] [float] NULL,
      [po_Odm_OrjDtut8] [float] NULL,
      [po_Odm_AnaDtut9] [float] NULL,
      [po_Odm_OrjDtut9] [float] NULL,
      [po_Odm_AnaDtut10] [float] NULL,
      [po_Odm_OrjDtut10] [float] NULL,
      [po_Odm_AnaDtut11] [float] NULL,
      [po_Odm_OrjDtut11] [float] NULL,
      [po_Odm_AnaDtut12] [float] NULL,
      [po_Odm_OrjDtut12] [float] NULL,
      [po_Odm_AnaDtut13] [float] NULL,
      [po_Odm_OrjDtut13] [float] NULL,
      [po_Odm_AnaDtut14] [float] NULL,
      [po_Odm_OrjDtut14] [float] NULL,
      [po_Odm_AnaDtut15] [float] NULL,
      [po_Odm_OrjDtut15] [float] NULL,
      [po_Odm_AnaDtut16] [float] NULL,
      [po_Odm_OrjDtut16] [float] NULL,
      [po_Odm_AnaDtut17] [float] NULL,
      [po_Odm_OrjDtut17] [float] NULL,
      [po_Odm_AnaDtut18] [float] NULL,
      [po_Odm_OrjDtut18] [float] NULL,
      [po_Odm_AnaDtut19] [float] NULL,
      [po_Odm_OrjDtut19] [float] NULL,
      [po_Odm_AnaDtut20] [float] NULL,
      [po_Odm_OrjDtut20] [float] NULL,
      [po_Odm_AnaDtut21] [float] NULL,
      [po_Odm_OrjDtut21] [float] NULL,
      [po_Odm_AnaDtut22] [float] NULL,
      [po_Odm_OrjDtut22] [float] NULL,
      [po_Odm_AnaDtut23] [float] NULL,
      [po_Odm_OrjDtut23] [float] NULL,
      [po_Odm_AnaDtut24] [float] NULL,
      [po_Odm_OrjDtut24] [float] NULL,
      [po_Odm_AnaDtut25] [float] NULL,
      [po_Odm_OrjDtut25] [float] NULL,
      [po_Odm_AnaDtut26] [float] NULL,
      [po_Odm_OrjDtut26] [float] NULL,
      [po_Odm_AnaDtut27] [float] NULL,
      [po_Odm_OrjDtut27] [float] NULL,
      [po_Odm_AnaDtut28] [float] NULL,
      [po_Odm_OrjDtut28] [float] NULL,
      [po_Odm_AnaDtut29] [float] NULL,
      [po_Odm_OrjDtut29] [float] NULL,
      [po_Odm_AnaDtut30] [float] NULL,
      [po_Odm_OrjDtut30] [float] NULL,
      [po_Odm_AnaDtut31] [float] NULL,
      [po_Odm_OrjDtut31] [float] NULL,
      [po_Odm_AnaDtut32] [float] NULL,
      [po_Odm_OrjDtut32] [float] NULL,
      [po_Odm_AnaDtut33] [float] NULL,
      [po_Odm_OrjDtut33] [float] NULL,
      [po_Odm_AnaDtut34] [float] NULL,
      [po_Odm_OrjDtut34] [float] NULL,
      [po_Odm_AnaDtut35] [float] NULL,
      [po_Odm_OrjDtut35] [float] NULL,
      [po_Odm_AnaDtut36] [float] NULL,
      [po_Odm_OrjDtut36] [float] NULL,
      [po_Odm_AnaDtut37] [float] NULL,
      [po_Odm_OrjDtut37] [float] NULL,
      [po_Odm_AnaDtut38] [float] NULL,
      [po_Odm_OrjDtut38] [float] NULL,
      [po_Odm_AnaDtut39] [float] NULL,
      [po_Odm_OrjDtut39] [float] NULL,
      [po_Odm_AnaDtut40] [float] NULL,
      [po_Odm_OrjDtut40] [float] NULL,
      [po_Odm_AnaDtut41] [float] NULL,
      [po_Odm_OrjDtut41] [float] NULL,
      [po_Odm_AnaDtut42] [float] NULL,
      [po_Odm_OrjDtut42] [float] NULL,
      [po_Odm_AnaDtut43] [float] NULL,
      [po_Odm_OrjDtut43] [float] NULL,
      [po_Odm_AnaDtut44] [float] NULL,
      [po_Odm_OrjDtut44] [float] NULL,
      [po_Odm_AnaDtut45] [float] NULL,
      [po_Odm_OrjDtut45] [float] NULL,
      [po_Odm_AnaDtut46] [float] NULL,
      [po_Odm_OrjDtut46] [float] NULL,
      [po_Odm_AnaDtut47] [float] NULL,
      [po_Odm_OrjDtut47] [float] NULL,
      [po_Odm_AnaDtut48] [float] NULL,
      [po_Odm_OrjDtut48] [float] NULL,
      [po_Odm_AnaDtut49] [float] NULL,
      [po_Odm_OrjDtut49] [float] NULL,
      [po_Odm_AnaDtut50] [float] NULL,
      [po_Odm_OrjDtut50] [float] NULL,
      [po_Vadeler_OdemeTipi1] [tinyint] NULL,
      [po_Vadeler_vade1] [datetime] NULL,
      [po_Vadeler_Tutar1] [float] NULL,
      [po_Vadeler_OdemeTipi2] [tinyint] NULL,
      [po_Vadeler_vade2] [datetime] NULL,
      [po_Vadeler_Tutar2] [float] NULL,
      [po_Vadeler_OdemeTipi3] [tinyint] NULL,
      [po_Vadeler_vade3] [datetime] NULL,
      [po_Vadeler_Tutar3] [float] NULL,
      [po_Vadeler_OdemeTipi4] [tinyint] NULL,
      [po_Vadeler_vade4] [datetime] NULL,
      [po_Vadeler_Tutar4] [float] NULL,
      [po_Vadeler_OdemeTipi5] [tinyint] NULL,
      [po_Vadeler_vade5] [datetime] NULL,
      [po_Vadeler_Tutar5] [float] NULL,
      [po_Vadeler_OdemeTipi6] [tinyint] NULL,
      [po_Vadeler_vade6] [datetime] NULL,
      [po_Vadeler_Tutar6] [float] NULL,
      [po_Vadeler_OdemeTipi7] [tinyint] NULL,
      [po_Vadeler_vade7] [datetime] NULL,
      [po_Vadeler_Tutar7] [float] NULL,
      [po_Vadeler_OdemeTipi8] [tinyint] NULL,
      [po_Vadeler_vade8] [datetime] NULL,
      [po_Vadeler_Tutar8] [float] NULL,
      [po_Vadeler_OdemeTipi9] [tinyint] NULL,
      [po_Vadeler_vade9] [datetime] NULL,
      [po_Vadeler_Tutar9] [float] NULL,
      [po_Vadeler_OdemeTipi10] [tinyint] NULL,
      [po_Vadeler_vade10] [datetime] NULL,
      [po_Vadeler_Tutar10] [float] NULL,
      [po_Vadeler_OdemeTipi11] [tinyint] NULL,
      [po_Vadeler_vade11] [datetime] NULL,
      [po_Vadeler_Tutar11] [float] NULL,
      [po_Vadeler_OdemeTipi12] [tinyint] NULL,
      [po_Vadeler_vade12] [datetime] NULL,
      [po_Vadeler_Tutar12] [float] NULL,
      [po_Vadeler_OdemeTipi13] [tinyint] NULL,
      [po_Vadeler_vade13] [datetime] NULL,
      [po_Vadeler_Tutar13] [float] NULL,
      [po_Vadeler_OdemeTipi14] [tinyint] NULL,
      [po_Vadeler_vade14] [datetime] NULL,
      [po_Vadeler_Tutar14] [float] NULL,
      [po_Vadeler_OdemeTipi15] [tinyint] NULL,
      [po_Vadeler_vade15] [datetime] NULL,
      [po_Vadeler_Tutar15] [float] NULL,
      [po_Vadeler_OdemeTipi16] [tinyint] NULL,
      [po_Vadeler_vade16] [datetime] NULL,
      [po_Vadeler_Tutar16] [float] NULL,
      [po_Vadeler_OdemeTipi17] [tinyint] NULL,
      [po_Vadeler_vade17] [datetime] NULL,
      [po_Vadeler_Tutar17] [float] NULL,
      [po_Vadeler_OdemeTipi18] [tinyint] NULL,
      [po_Vadeler_vade18] [datetime] NULL,
      [po_Vadeler_Tutar18] [float] NULL,
      [po_Vadeler_OdemeTipi19] [tinyint] NULL,
      [po_Vadeler_vade19] [datetime] NULL,
      [po_Vadeler_Tutar19] [float] NULL,
      [po_Vadeler_OdemeTipi20] [tinyint] NULL,
      [po_Vadeler_vade20] [datetime] NULL,
      [po_Vadeler_Tutar20] [float] NULL,
      [po_Vadeler_OdemeTipi21] [tinyint] NULL,
      [po_Vadeler_vade21] [datetime] NULL,
      [po_Vadeler_Tutar21] [float] NULL,
      [po_Vadeler_OdemeTipi22] [tinyint] NULL,
      [po_Vadeler_vade22] [datetime] NULL,
      [po_Vadeler_Tutar22] [float] NULL,
      [po_Vadeler_OdemeTipi23] [tinyint] NULL,
      [po_Vadeler_vade23] [datetime] NULL,
      [po_Vadeler_Tutar23] [float] NULL,
      [po_Vadeler_OdemeTipi24] [tinyint] NULL,
      [po_Vadeler_vade24] [datetime] NULL,
      [po_Vadeler_Tutar24] [float] NULL,
      [po_Vadeler_OdemeTipi25] [tinyint] NULL,
      [po_Vadeler_vade25] [datetime] NULL,
      [po_Vadeler_Tutar25] [float] NULL,
      [po_Vadeler_OdemeTipi26] [tinyint] NULL,
      [po_Vadeler_vade26] [datetime] NULL,
      [po_Vadeler_Tutar26] [float] NULL,
      [po_Vadeler_OdemeTipi27] [tinyint] NULL,
      [po_Vadeler_vade27] [datetime] NULL,
      [po_Vadeler_Tutar27] [float] NULL,
      [po_Vadeler_OdemeTipi28] [tinyint] NULL,
      [po_Vadeler_vade28] [datetime] NULL,
      [po_Vadeler_Tutar28] [float] NULL,
      [po_Vadeler_OdemeTipi29] [tinyint] NULL,
      [po_Vadeler_vade29] [datetime] NULL,
      [po_Vadeler_Tutar29] [float] NULL,
      [po_Vadeler_OdemeTipi30] [tinyint] NULL,
      [po_Vadeler_vade30] [datetime] NULL,
      [po_Vadeler_Tutar30] [float] NULL,
      [po_Vadeler_OdemeTipi31] [tinyint] NULL,
      [po_Vadeler_vade31] [datetime] NULL,
      [po_Vadeler_Tutar31] [float] NULL,
      [po_Vadeler_OdemeTipi32] [tinyint] NULL,
      [po_Vadeler_vade32] [datetime] NULL,
      [po_Vadeler_Tutar32] [float] NULL,
      [po_Vadeler_OdemeTipi33] [tinyint] NULL,
      [po_Vadeler_vade33] [datetime] NULL,
      [po_Vadeler_Tutar33] [float] NULL,
      [po_Vadeler_OdemeTipi34] [tinyint] NULL,
      [po_Vadeler_vade34] [datetime] NULL,
      [po_Vadeler_Tutar34] [float] NULL,
      [po_Vadeler_OdemeTipi35] [tinyint] NULL,
      [po_Vadeler_vade35] [datetime] NULL,
      [po_Vadeler_Tutar35] [float] NULL,
      [po_Vadeler_OdemeTipi36] [tinyint] NULL,
      [po_Vadeler_vade36] [datetime] NULL,
      [po_Vadeler_Tutar36] [float] NULL,
      [po_Tks_Satis] [bit] NULL,
      [po_Tks_Satis_Tutar] [float] NULL,
      [po_Odm_TaksitTipi1] [tinyint] NULL,
      [po_Odm_TaksitTipi2] [tinyint] NULL,
      [po_Odm_TaksitTipi3] [tinyint] NULL,
      [po_Odm_TaksitTipi4] [tinyint] NULL,
      [po_Odm_TaksitTipi5] [tinyint] NULL,
      [po_Odm_TaksitTipi6] [tinyint] NULL,
      [po_Odm_TaksitTipi7] [tinyint] NULL,
      [po_Odm_TaksitTipi8] [tinyint] NULL,
      [po_Odm_TaksitTipi9] [tinyint] NULL,
      [po_Odm_TaksitTipi10] [tinyint] NULL,
      [po_Odm_TaksitTipi11] [tinyint] NULL,
      [po_Odm_TaksitTipi12] [tinyint] NULL,
      [po_Odm_TaksitTipi13] [tinyint] NULL,
      [po_Odm_TaksitTipi14] [tinyint] NULL,
      [po_Odm_TaksitTipi15] [tinyint] NULL,
      [po_Odm_TaksitTipi16] [tinyint] NULL,
      [po_Odm_TaksitTipi17] [tinyint] NULL,
      [po_Odm_TaksitTipi18] [tinyint] NULL,
      [po_Odm_TaksitTipi19] [tinyint] NULL,
      [po_Odm_TaksitTipi20] [tinyint] NULL,
      [po_Odm_TaksitTipi21] [tinyint] NULL,
      [po_Odm_TaksitTipi22] [tinyint] NULL,
      [po_Odm_TaksitTipi23] [tinyint] NULL,
      [po_Odm_TaksitTipi24] [tinyint] NULL,
      [po_Odm_TaksitTipi25] [tinyint] NULL,
      [po_Odm_TaksitTipi26] [tinyint] NULL,
      [po_Odm_TaksitTipi27] [tinyint] NULL,
      [po_Odm_TaksitTipi28] [tinyint] NULL,
      [po_Odm_TaksitTipi29] [tinyint] NULL,
      [po_Odm_TaksitTipi30] [tinyint] NULL,
      [po_Odm_TaksitTipi31] [tinyint] NULL,
      [po_Odm_TaksitTipi32] [tinyint] NULL,
      [po_Odm_TaksitTipi33] [tinyint] NULL,
      [po_Odm_TaksitTipi34] [tinyint] NULL,
      [po_Odm_TaksitTipi35] [tinyint] NULL,
      [po_Odm_TaksitTipi36] [tinyint] NULL,
      [po_Odm_TaksitTipi37] [tinyint] NULL,
      [po_Odm_TaksitTipi38] [tinyint] NULL,
      [po_Odm_TaksitTipi39] [tinyint] NULL,
      [po_Odm_TaksitTipi40] [tinyint] NULL,
      [po_Odm_TaksitTipi41] [tinyint] NULL,
      [po_Odm_TaksitTipi42] [tinyint] NULL,
      [po_Odm_TaksitTipi43] [tinyint] NULL,
      [po_Odm_TaksitTipi44] [tinyint] NULL,
      [po_Odm_TaksitTipi45] [tinyint] NULL,
      [po_Odm_TaksitTipi46] [tinyint] NULL,
      [po_Odm_TaksitTipi47] [tinyint] NULL,
      [po_Odm_TaksitTipi48] [tinyint] NULL,
      [po_Odm_TaksitTipi49] [tinyint] NULL,
      [po_Odm_TaksitTipi50] [tinyint] NULL,
      [po_OdemeNo1] [tinyint] NULL,
      [po_ProvizyonKodu1] [nvarchar](10) NULL,
      [po_ProvizyonTutari1] [float] NULL,
      [po_OdemeNo2] [tinyint] NULL,
      [po_ProvizyonKodu2] [nvarchar](10) NULL,
      [po_ProvizyonTutari2] [float] NULL,
      [po_OdemeNo3] [tinyint] NULL,
      [po_ProvizyonKodu3] [nvarchar](10) NULL,
      [po_ProvizyonTutari3] [float] NULL,
      [po_OdemeNo4] [tinyint] NULL,
      [po_ProvizyonKodu4] [nvarchar](10) NULL,
      [po_ProvizyonTutari4] [float] NULL,
      [po_OdemeNo5] [tinyint] NULL,
      [po_ProvizyonKodu5] [nvarchar](10) NULL,
      [po_ProvizyonTutari5] [float] NULL,
      [po_OdemeNo6] [tinyint] NULL,
      [po_ProvizyonKodu6] [nvarchar](10) NULL,
      [po_ProvizyonTutari6] [float] NULL,
      [po_Tahsilat_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [po_Tahsilat_evrakno_sira] [int] NULL,
      [po_Tahsilat_Tutari] [float] NULL,
      [po_ParaUstuOdemeTipi] [tinyint] NULL,
      [po_ParaUstuAnaDtut] [float] NULL,
      [po_ParaUstuOrjDtut] [float] NULL,
      [po_EvrakID] [nvarchar](40) NULL,
      [po_AdresNo] [int] NULL,
      [po_EArsivSeri] [nvarchar](7) NULL,
      [po_EArsivSira] [int] NULL,
      [po_ZNo] [int] NULL,
      [po_FNo] [int] NULL,
      [po_EJNo] [int] NULL,
      [po_OKCEvrakID] [nvarchar](40) NULL,
      [po_YolcuBeraberKod] [nvarchar](25) NULL,
      [po_YolcuBeraberIstisnaKodu] [nvarchar](5) NULL,
      [po_YolcuBeraberAraciKurumKodu] [nvarchar](25) NULL,
      [po_GibeGonderildiFl] [bit] NULL,
      [po_KayitSiraNo] [int] IDENTITY(1,1) NOT NULL,
    CONSTRAINT [NDX_O_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [po_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];
    
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [po_Guid];
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [po_DBCno];
    ALTER TABLE [dbo].[O_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [po_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'03d' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'O_${tarih}_${depoNo}';
    CREATE UNIQUE NONCLUSTERED INDEX [NDX_O_${tarih}_${depoNo}_02] ON [dbo].[O_${tarih}_${depoNo}]([po_KasaKodu] ASC,[po_BelgeNo] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
  END
    `
  return q
}

exports.workDataV17CreateSTHQuery = function (tarih, depoNo) {
  tarih = util.yyyyMMdd(tarih)
  depoNo = util.pad(depoNo, 3)
  let q = `
    SET ANSI_NULLS ON;
    SET QUOTED_IDENTIFIER ON;
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE type='U' and name='S_${tarih}_${depoNo}') BEGIN
    CREATE TABLE [dbo].[S_${tarih}_${depoNo}](
    	[sth_Guid] [uniqueidentifier] NOT NULL,
      [sth_DBCno] [smallint] NOT NULL,
      [sth_SpecRECno] [int] NULL,
      [sth_iptal] [bit] NULL,
      [sth_fileid] [smallint] NULL,
      [sth_hidden] [bit] NULL,
      [sth_kilitli] [bit] NULL,
      [sth_degisti] [bit] NULL,
      [sth_checksum] [int] NULL,
      [sth_create_user] [smallint] NULL,
      [sth_create_date] [datetime] NOT NULL,
      [sth_lastup_user] [smallint] NULL,
      [sth_lastup_date] [datetime] NULL,
      [sth_special1] [nvarchar](127) NULL,
      [sth_special2] [nvarchar](127) NULL,
      [sth_special3] [nvarchar](127) NULL,
      [sth_MainProgramNo] [smallint] NULL,
      [sth_VersionNo] [nvarchar](10) NULL,
      [sth_MenuNo] [nvarchar](10) NULL,
      [sth_MikroSpecial1] [nvarchar](40) NULL,
      [sth_MikroSpecial2] [nvarchar](40) NULL,
      [sth_MikroSpecial3] [nvarchar](40) NULL,
      [sth_ExternalProgramType] [tinyint] NULL,
      [sth_ExternalProgramId] [nvarchar](127) NULL,
      [sth_Hash] [bigint] NULL,
      [sth_firmano] [int] NULL,
      [sth_subeno] [int] NULL,
      [sth_tarih] [datetime] NULL,
      [sth_tip] [tinyint] NULL,
      [sth_cins] [tinyint] NULL,
      [sth_normal_iade] [tinyint] NULL,
      [sth_evraktip] [tinyint] NULL,
      [sth_evrakno_seri] [dbo].[evrakseri_str] NULL,
      [sth_evrakno_sira] [int] NULL,
      [sth_satirno] [int] NULL,
      [sth_belge_no] [dbo].[belgeno_str] NULL,
      [sth_belge_tarih] [datetime] NULL,
      [sth_stok_kod] [nvarchar](25) NULL,
      [sth_isk_mas1] [tinyint] NULL,
      [sth_isk_mas2] [tinyint] NULL,
      [sth_isk_mas3] [tinyint] NULL,
      [sth_isk_mas4] [tinyint] NULL,
      [sth_isk_mas5] [tinyint] NULL,
      [sth_isk_mas6] [tinyint] NULL,
      [sth_isk_mas7] [tinyint] NULL,
      [sth_isk_mas8] [tinyint] NULL,
      [sth_isk_mas9] [tinyint] NULL,
      [sth_isk_mas10] [tinyint] NULL,
      [sth_sat_iskmas1] [bit] NULL,
      [sth_sat_iskmas2] [bit] NULL,
      [sth_sat_iskmas3] [bit] NULL,
      [sth_sat_iskmas4] [bit] NULL,
      [sth_sat_iskmas5] [bit] NULL,
      [sth_sat_iskmas6] [bit] NULL,
      [sth_sat_iskmas7] [bit] NULL,
      [sth_sat_iskmas8] [bit] NULL,
      [sth_sat_iskmas9] [bit] NULL,
      [sth_sat_iskmas10] [bit] NULL,
      [sth_pos_satis] [tinyint] NULL,
      [sth_promosyon_fl] [bit] NULL,
      [sth_cari_cinsi] [tinyint] NULL,
      [sth_cari_kodu] [nvarchar](25) NULL,
      [sth_cari_grup_no] [tinyint] NULL,
      [sth_isemri_gider_kodu] [nvarchar](25) NULL,
      [sth_plasiyer_kodu] [nvarchar](25) NULL,
      [sth_har_doviz_cinsi] [tinyint] NULL,
      [sth_har_doviz_kuru] [float] NULL,
      [sth_alt_doviz_kuru] [float] NULL,
      [sth_stok_doviz_cinsi] [tinyint] NULL,
      [sth_stok_doviz_kuru] [float] NULL,
      [sth_miktar] [float] NULL,
      [sth_miktar2] [float] NULL,
      [sth_birim_pntr] [tinyint] NULL,
      [sth_birimfiyat] [float] NULL,
      [sth_tutar] [float] NULL,
      [sth_iskonto1] [float] NULL,
      [sth_iskonto2] [float] NULL,
      [sth_iskonto3] [float] NULL,
      [sth_iskonto4] [float] NULL,
      [sth_iskonto5] [float] NULL,
      [sth_iskonto6] [float] NULL,
      [sth_masraf1] [float] NULL,
      [sth_masraf2] [float] NULL,
      [sth_masraf3] [float] NULL,
      [sth_masraf4] [float] NULL,
      [sth_vergi_pntr] [tinyint] NULL,
      [sth_vergi] [float] NULL,
      [sth_masraf_vergi_pntr] [tinyint] NULL,
      [sth_masraf_vergi] [float] NULL,
      [sth_netagirlik] [float] NULL,
      [sth_odeme_op] [int] NULL,
      [sth_aciklama] [nvarchar](50) NULL,
      [sth_sip_uid] [uniqueidentifier] NULL,
      [sth_fat_uid] [uniqueidentifier] NULL,
      [sth_giris_depo_no] [int] NULL,
      [sth_cikis_depo_no] [int] NULL,
      [sth_malkbl_sevk_tarihi] [datetime] NULL,
      [sth_cari_srm_merkezi] [nvarchar](25) NULL,
      [sth_stok_srm_merkezi] [nvarchar](25) NULL,
      [sth_fis_tarihi] [datetime] NULL,
      [sth_fis_sirano] [int] NULL,
      [sth_vergisiz_fl] [bit] NULL,
      [sth_maliyet_ana] [float] NULL,
      [sth_maliyet_alternatif] [float] NULL,
      [sth_maliyet_orjinal] [float] NULL,
      [sth_adres_no] [int] NULL,
      [sth_parti_kodu] [nvarchar](25) NULL,
      [sth_lot_no] [int] NULL,
      [sth_kons_uid] [uniqueidentifier] NULL,
      [sth_proje_kodu] [nvarchar](25) NULL,
      [sth_exim_kodu] [nvarchar](25) NULL,
      [sth_otv_pntr] [tinyint] NULL,
      [sth_otv_vergi] [float] NULL,
      [sth_brutagirlik] [float] NULL,
      [sth_disticaret_turu] [tinyint] NULL,
      [sth_otvtutari] [float] NULL,
      [sth_otvvergisiz_fl] [bit] NULL,
      [sth_oiv_pntr] [tinyint] NULL,
      [sth_oiv_vergi] [float] NULL,
      [sth_oivvergisiz_fl] [bit] NULL,
      [sth_fiyat_liste_no] [int] NULL,
      [sth_oivtutari] [float] NULL,
      [sth_Tevkifat_turu] [tinyint] NULL,
      [sth_nakliyedeposu] [int] NULL,
      [sth_nakliyedurumu] [tinyint] NULL,
      [sth_yetkili_uid] [uniqueidentifier] NULL,
      [sth_taxfree_fl] [bit] NULL,
      [sth_ilave_edilecek_kdv] [float] NULL,
      [sth_ismerkezi_kodu] [nvarchar](25) NULL,
      [sth_HareketGrupKodu1] [nvarchar](25) NULL,
      [sth_HareketGrupKodu2] [nvarchar](25) NULL,
      [sth_HareketGrupKodu3] [nvarchar](25) NULL,
      [sth_Olcu1] [float] NULL,
      [sth_Olcu2] [float] NULL,
      [sth_Olcu3] [float] NULL,
      [sth_Olcu4] [float] NULL,
      [sth_Olcu5] [float] NULL,
      [sth_FormulMiktarNo] [tinyint] NULL,
      [sth_FormulMiktar] [float] NULL,
      [sth_eirs_senaryo] [tinyint] NULL,
      [sth_eirs_tipi] [tinyint] NULL,
      [sth_teslim_tarihi] [datetime] NULL,
      [sth_matbu_fl] [bit] NULL,
      [sth_satis_fiyat_doviz_cinsi] [tinyint] NULL,
      [sth_satis_fiyat_doviz_kuru] [float] NULL,
      [sth_eticaret_kanal_kodu] [nvarchar](25) NULL,
      [sth_bagli_ithalat_kodu] [nvarchar](25) NULL,
      [sth_tevkifat_sifirlandi_fl] [bit] NULL,
    CONSTRAINT [NDX_S_${tarih}_${depoNo}_00] PRIMARY KEY CLUSTERED 
    (
      [sth_Guid] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT (newid()) FOR [sth_Guid];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT ((0)) FOR [sth_DBCno];
    ALTER TABLE [dbo].[S_${tarih}_${depoNo}] ADD  DEFAULT (getdate()) FOR [sth_create_date];
    EXEC sys.sp_addextendedproperty @name=N'version', @value=N'03d' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'S_${tarih}_${depoNo}';
    CREATE UNIQUE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_05] ON [dbo].[S_${tarih}_${depoNo}]
    (
      [sth_evraktip] ASC,
      [sth_evrakno_seri] ASC,
      [sth_evrakno_sira] ASC,
      [sth_satirno] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_02] ON [dbo].[S_${tarih}_${depoNo}] ([sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_03] ON [dbo].[S_${tarih}_${depoNo}]([sth_cari_cinsi] ASC,[sth_cari_kodu] ASC,[sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_04] ON [dbo].[S_${tarih}_${depoNo}]([sth_stok_kod] ASC,	[sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_06] ON [dbo].[S_${tarih}_${depoNo}]([sth_plasiyer_kodu] ASC,[sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_07] ON [dbo].[S_${tarih}_${depoNo}]([sth_fat_uid] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_08] ON [dbo].[S_${tarih}_${depoNo}]([sth_sip_uid] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_10] ON [dbo].[S_${tarih}_${depoNo}]([sth_cari_cinsi] ASC,[sth_cari_kodu] ASC,[sth_stok_kod] ASC,[sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_11] ON [dbo].[S_${tarih}_${depoNo}]([sth_stok_kod] ASC,	[sth_cari_cinsi] ASC,[sth_cari_kodu] ASC,[sth_tarih] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_12] ON [dbo].[S_${tarih}_${depoNo}]([sth_exim_kodu] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_13] ON [dbo].[S_${tarih}_${depoNo}]([sth_isemri_gider_kodu] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_14] ON [dbo].[S_${tarih}_${depoNo}]([sth_stok_kod] ASC,[sth_cins] ASC)INCLUDE([sth_tarih],[sth_tip],[sth_miktar],[sth_giris_depo_no],[sth_cikis_depo_no]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
    CREATE NONCLUSTERED INDEX [NDX_S_${tarih}_${depoNo}_15] ON [dbo].[S_${tarih}_${depoNo}]([sth_kons_uid] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
  END
    `
  return q
}

